version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
      - '3000:3000'
    depends_on:
      - server
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /app/build
      - ./server:/app
    environment:
      - FIREHOSE_ACCESS_KEY_ID=${FIREHOSE_ACCESS_KEY_ID}
      - FIREHOSE_SECRET_ACCESS_KEY=${FIREHOSE_SECRET_ACCESS_KEY}
